### ISSUE TITLE
teste1

### ISSUE THREAD

**Issue by wgr-leao10** [wgr-leao10/Plataforma_Curso_Video#1]
Aqui seria um teste para aula 09 do curso de git e GitHub

**Comment by wagnerribeiro-dev** [comment]
Teste feito com sucesso
@contas criadas com sucesso

**Comment by wgr-leao10** [comment]
teste realizado com sucesso
Muito obrigado pela sua colaboração!! Meu contato no [Linkedin]([linkedin.com/in/wagnergoncalvesribeiro](https://www.linkedin.com/in/wagnergoncalvesribeiro))
